### ISSUE TITLE
大佬 最终提交 json不成功吖，求大佬解惑

### ISSUE THREAD

**Issue by Zhuliang1** [MasterKenway/DGUT-yqfk#2]
![image](https://user-images.githubusercontent.com/25604870/94384190-89859800-0174-11eb-8bd7-3dc5796ed03c.png)

**Comment by MasterKenway** [comment]
在回校之后新增的部分字段数据似乎会出问题 导致提交表单失败 具体情况需要我有空抓包看看

**Comment by MasterKenway** [comment]
问题已经由 chuangzhu 同学帮忙修复 
详情请见：https://github.com/MasterKenway/DGUT-yqfk/pull/3#issue-498096512
